# Generated by Django 4.2.8 on 2023-12-21 22:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=150, verbose_name='название награды')),
                ('prize_description', models.TextField(blank=True, null=True, verbose_name='описание награды')),
                ('prize_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'награда',
                'verbose_name_plural': 'награды',
                'ordering': ('prize_name',),
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_user', models.CharField(max_length=100, verbose_name='пользователь')),
                ('habit_name', models.CharField(max_length=150, verbose_name='название привычки')),
                ('habit_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='место выполнения привычки')),
                ('habit_time', models.TimeField(blank=True, null=True, verbose_name='время выполнения привычки')),
                ('habit_action', models.CharField(max_length=200, verbose_name='действие привычки')),
                ('habit_is_nice', models.BooleanField(default=True, verbose_name='признак приятной привычки')),
                ('habit_period', models.CharField(choices=[('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно')], default='ежедневно', max_length=20, verbose_name='периодичность привычки')),
                ('habit_duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='продолжительность выполнения привычки')),
                ('habit_is_public', models.BooleanField(default=True, verbose_name='признак публичной привычки')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habbits.habit', verbose_name='связанная привычка')),
                ('habit_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('habit_prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habbits.prize', verbose_name='приз')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('habit_name',),
            },
        ),
    ]
